### ISSUE TITLE
PHPStorm, unit test compatibility.

### ISSUE THREAD

**Issue by tareiking** [Chassis/Fish#8]
PHPStorm uses bash specific commands to run some PHPUnit commands internally.

Specifically, selective tests run something similar to:

```
vagrant:///Users/Tarei/Work/ffxblue/usr/bin/php -dxdebug.remote_enable=1 -dxdebug.remote_mode=req -dxdebug.remote_port=9000 -dxdebug.remote_host=10.0.2.2 /usr/local/bin/phpunit --configuration /vagrant/content/phpunit.xml --filter "/::test_adding_image( .*)?$/" Project_Api_Content_Images /vagrant/content/.tests/tests/plugins/project-api-content/test-api-content-media.php --teamcity
Testing started at 18:19 ...
```

Fish doesn't support `/::test_adding_image( .*)?$/` syntax, so will complete tests prematurely. In order to support PHPUnit tests, you can remove this extension and use: `chsh` to switch back to bash shell.

PHPStorm version: 2017.1
PHPUnit version: 5.6.3 and 4.8.

**Comment by rmccue** [comment]
Hmmmmmm. This `--filter` command should be inside PHPUnit, not using the shell, so not sure how this is occurring?

**Comment by tareiking** [comment]
It appears PHPStorm is using `vagrant ssh` and then copypasta these commands via the default shell for the VM. Which when using this extension is `fish`.

Support really needs to be done on the PHPStorm end, but raising as an issue for other users who might come up against it.

Feel free to close sir!
